### ISSUE TITLE
`Uncaught ReferenceError: global is not defined`

### ISSUE THREAD

**Issue by maxcountryman** [sagi/workers-slack#22]
I can't seem to actually import this into a worker. Here's the error I see:

```
✘ [ERROR] Error on remote worker: ParseError: A request to the Cloudflare API (/accounts/fb15ed8606dd6b410e7876fbcfd3b4b7/workers/scripts/worker-typescript-template/edge-preview) failed.

      at throwFetchError
  (/Users/max/Projects/costbeacon/node_modules/wrangler/wrangler-dist/cli.js:141293:17)
      at fetchResult
  (/Users/max/Projects/costbeacon/node_modules/wrangler/wrangler-dist/cli.js:141262:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async createPreviewToken
  (/Users/max/Projects/costbeacon/node_modules/wrangler/wrangler-dist/cli.js:141555:29)
      at async createWorkerPreview
  (/Users/max/Projects/costbeacon/node_modules/wrangler/wrangler-dist/cli.js:141575:17)
      at async start
  (/Users/max/Projects/costbeacon/node_modules/wrangler/wrangler-dist/cli.js:142271:34) {
    text: 'A request to the Cloudflare API
  (/accounts/fb15ed8606dd6b410e7876fbcfd3b4b7/workers/scripts/worker-typescript-template/edge-preview)
  failed.',
    notes: [
      {
        text: 'Uncaught ReferenceError: global is not defined\n' +
          '  at index.js:336:7 in node_modules/@sagi.io/workers-slack/dist/main.js\n' +
          '  at index.js:11:50 in __require\n' +
          '  at index.js:781:36\n' +
          ' [code: 10021]'
      }
    ],
    location: undefined,
    kind: 'error',
    code: 10021
  }
```

**Comment by sagi** [comment]
Apologies, this library is built to be used both for Cloudflare Workers and Node.js (for which we need `globals`). I added a note about the `node_compat` flag in `README.md` and published `v0.0.55`.

If you have any thoughts on how to fix this issue (and still make it work for both envs) please let me know.
